### PR TITLE
Fix deadlock if callback invokes Subscribe

### PR DESCRIPTION
**Pull request by bonan**
In the `matchAndDispatch()` loop, a read lock is aquired when iterating through routes and matching.
Any callbacks found are currently invoked directly, with the read lock in place. If anyones tries to subscribe to additional topics (with callback) from a callback - there will be a deadlock since `addRoute` will try to aquire a write lock.

Fix: Call RUnlock() before invoking route callback to avoid deadlock if callback invokes Subscribe()

### CODE REVIEW

**Comment by alsm** [comment]
Hi, thanks for the PR and spotting this issue, please sign the Eclipse CLA and sign off your submission so I can merge it, or let me know if this isn't possible and I'll fix the issue directly.

**Comment by bonan** [comment]
I'm getting this message when trying to sign:
```Error, An error has occured and your Eclipse Contributor Agreement was not submitted. (ECA-03)```

I tried both yesterday and today without any luck.

I notified the license@ mailbox, who forwarded it to webmaster@ - no response from there yet

**Comment by bonan** [comment]
The CLA issue is resolved, and I re-commited the fix with sign off

**Comment by alsm** [comment]
Thanks for this.

**Comment by daenney** [comment]
Any chance we could get a point release, 1.3.1 or something along those lines? It would be nice not to have to pin on master and resolving a deadlock would seem to warrant a release.

**Pull request merged**
