### PR TITLE
Add throttling option

### PR DESCRIPTION
**Pull request by johnhydroware**
Make it possible to throttle maximum number of messages sent per second.

### CODE REVIEW

**Comment by alsm** [comment]
I appreciate you trying to add this kind of function to the client, I know it would be useful for services like AWS IoT, but I'm not sure about this implementation. 1 message every 1/x seconds isn't quite the same as x messages per second.

**Comment by johnhydroware** [comment]
> I appreciate you trying to add this kind of function to the client, I know it would be useful for services like AWS IoT, but I'm not sure about this implementation. 1 message every 1/x seconds isn't quite the same as x messages per second.

Would this functionality be accepted if I changed the implementation so that it was strictly x messages per second? If so, I will take a look at doing it that way.

**Comment by alsm** [comment]
Yes, I was thinking how this might be done in the new v5 client, have you seen https://godoc.org/golang.org/x/time/rate this might help.

**Comment by johnhydroware** [comment]
> Yes, I was thinking how this might be done in the new v5 client, have you seen https://godoc.org/golang.org/x/time/rate this might help.

That will limit the average rate, not the peak. The documentation for AWS doesn't really say what it means by "requests per second" and it it difficult to test since it will just silently discard messages. Unless I can't find any good documentation on this I will probably not do anything more on this issue.

**Pull request closed without merging**
