### PR TITLE
Avoid race during shutdown that can deadlock

### PR DESCRIPTION
**Pull request by databus23**
This is a proposed fix for #83.
Its not super elegant as it drops a message that was received over the wire but its a simple solution that avoids a deadlock.

I'm open for suggestions how this could be solved better.

### CODE REVIEW

**Comment by alsm** [comment]
I thought of something similar yesterday. I'm not too concerned about a packet that arrives as we've already initiated shutdown, the response to a qos 1 or 2 packet isn't sent until the packet is handled in `alllogic`, so would/should be resent at reconnect.
I am concerned though about packets arriving while we're in a blocking function in `alllogic` such as `persistInbound` and throwing that away.
I'm not going to merge this for now until I can do some more testing/thinking. Equally if you come up with any other ideas please contribute. I probably won't be able to do much on this until April due to going away.

**Comment by databus23** [comment]
But this safeguard only kicks-in if ` <-c.stop` is returning something which means we are shutting down. If `c.ibound <- cp` blocks during normal operations that should be fine. As soon as `alllogic` enters a new loop it will read from `c.ibound` and the select in `incoming` will continue.

**Comment by databus23** [comment]
I think the main problem is that as soon as `c.stop` is closed there is no guarantee that something will read from `c.ibound` anymore as `alllogic` might have already exited.

**Comment by alsm** [comment]
Yes, of course, sorry I misread what you had done. In which case, as in my first comment, I'm not too concerned about potentially losing a message, qos 1/2 will be resent on reconnect, qos 0 has no delivery guarantee anyway (and often aren't queued up when clients are offline) so I don't think it'll have an impact on end users.
As such I am going to merge it, thanks for your work on this.

**Pull request merged**
