### PR TITLE
Fix: The acknowledgement for incoming messages are sent even if the associated MessageHandler panics #16

### PR DESCRIPTION
**Pull request by xeizmendi**
This is a proposed fix for #16

In this fix we delegate sending acks back to the user of the library by adding an Ack function to the Message interface. This means acks are only sent whenever we are really done processing the message.

### CODE REVIEW

**Comment by xeizmendi** [comment]
It's been almost a month since this PR was created.
Will it be reviewed at some point?

**Comment by aminehmida** [comment]
Any news regarding this PR?

**Comment by gm42** [comment]
Is there some documentation about how to use `Ack()`? I could not find any, nor any example.

I assume also that there is no `Nack()` equivalent.

**Comment by amuldowney** [comment]
I don't understand how this change fixes issue #16 . It looks like matchAndDispatch calls .Ack() after the handler is called no matter what. It doesn't seem like there is a way to fail a message.

**Comment by xeizmendi** [comment]
@gm42 @amuldowney unfortunately there is no way to fail a message, the MQTT protocol doesn't support this, it will eventually be sent again when the message times out. I stopped using MQTT because of this.

@aminehmida about the call to Ack, this was added later on by someone else because my PR changed the default behaviour. As in, you always need to acknowledge or else you will receive the message over and over again, you'll notice that in this PR Ack is not always called.
The correct way, I guess, would be to add an AutoAck option to the client so it's configurable and make it the default option.

**Comment by aminehmida** [comment]
@xeizmendi thanks for the clarification.

**Pull request merged**
